// <auto-generated />
using BankAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankAPI.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20231222175044_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("BankAPI.Entities.Tables.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccountEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1250.0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Balance = 50.0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Balance = 3.2599999999999998,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Balance = 150.0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Balance = 25123.0,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BankAPI.Entities.Tables.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "adam.anderson@gmail.com",
                            FirstName = "Adam",
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = 2,
                            Email = "billy.baker@gmail.com",
                            FirstName = "Billy",
                            LastName = "Baker"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carol.carson@gmail.com",
                            FirstName = "Carol",
                            LastName = "Carson"
                        });
                });

            modelBuilder.Entity("BankAPI.Entities.Tables.AccountEntity", b =>
                {
                    b.HasOne("BankAPI.Entities.Tables.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
